# ===== Heizung: Raum Badezimmer (Package) =====

input_boolean:
  heizung_badezimmer:
    name: Heizung Badezimmer

climate:
  - platform: generic_thermostat
    name: Heizung Badezimmer (extern)
    heater: input_boolean.heizung_badezimmer    # statt climate.thermostat_badezimmer
    target_sensor: sensor.thermometer_badeztimmer_temperature   # <- echter Temperatursensor
    min_temp: 5
    max_temp: 30
    target_temp: 20
    cold_tolerance: 0.3
    hot_tolerance: 0.3
    precision: 0.1
    target_temp_step: 0.1
    ac_mode: false
     
homeassistant:
  customize:
    sensor.thermometer_badeztimmer_temperature:
      display_precision: 1
    sensor.thermometer_badeztimmer_humidity:
      display_precision: 1
